export const categoriesData = [
    { category_name: 'Electronic Devices', parent: null },
    { category_name: 'TV & Home Appliances', parent: null },
    { category_name: 'Earphones', parent: 'Audio' },
    { category_name: 'Headphones', parent: 'Audio' },
    { category_name: 'Speaker', parent: 'Audio' },
    { category_name: 'Computer Mice', parent: 'Computer Peripherals' },
    { category_name: 'Keyboards', parent: 'Computer Peripherals' },
    { category_name: 'Mechanical Keyboard Key-caps', parent: 'Computer Peripherals' },
    { category_name: 'Mechanical Keyboard Switches', parent: 'Computer Peripherals' },
    { category_name: 'Monitors', parent: 'Computer Peripherals' },
    { category_name: 'Audio', parent: 'Electronic Devices' },
    { category_name: 'Computer Peripherals', parent: 'Electronic Devices' },
    { category_name: 'Computers', parent: 'Electronic Devices' },
    { category_name: 'Mobiles', parent: 'Electronic Devices' },
    { category_name: 'Mechanical Keyboards', parent: 'Keyboards' },
    { category_name: 'Large Appliances', parent: 'TV & Home Appliances' },
    { category_name: 'Small Appliances', parent: 'TV & Home Appliances' },
    { category_name: 'Televisions', parent: 'TV & Home Appliances' },
]