const mongoose = require("mongoose");
const { productSchema } = require("./schemas");

async function insertMockData(uri) {
  try {
    await mongoose.connect(uri);

    const Product = mongoose.model("Product", productSchema);
    await Product.insertMany([
      {
        sqlId: 1,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Width", value: 5 },
          { sqlId: "Length", value: 8 },
          { sqlId: "Thickness", value: 0.25 },
          { sqlId: "Color", value: "Red" },
          { sqlId: "RAM", value: "16GB" },
          { sqlId: "CPU", value: "Quad-core" },
          { sqlId: "Storage capacity", value: "256GB" },
          { sqlId: "Resolution", value: "1080p" },
        ],
      },
      {
        sqlId: 2,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Width", value: 5 },
          { sqlId: "Length", value: 8 },
          { sqlId: "Thickness", value: 0.25 },
          { sqlId: "Color", value: "Red" },
          { sqlId: "RAM", value: "16GB" },
          { sqlId: "CPU", value: "Quad-core" },
          { sqlId: "GPU", value: "Intel Graphic" },
          { sqlId: "Screen size", value: "20in" },
          { sqlId: "Storage capacity", value: "256GB" },
          { sqlId: "Resolution", value: "1080p" },
        ],
      },
      {
        sqlId: 3,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Key-cap profile", value: "Asdad" },
          { sqlId: "Color", value: "blue" },
          { sqlId: "Latency", value: "0.5ms" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
        ],
      },
      {
        sqlId: 4,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Color", value: "blue" },
          { sqlId: "Latency", value: "0.5ms" },
        ],
      },
      {
        sqlId: 5,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "BB" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Refresh rate", value: "120Hz" },
          { sqlId: "Resolution", value: "1080p" },
          { sqlId: "Screen size", value: "20in" },
        ],
      },
      {
        // There were no warranty, warranty period, and brand for id 6
        sqlId: 6,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Wireless", value: true },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Latency", value: "less than 1ms" },
          { sqlId: "Noise cancelling", value: true },
          { sqlId: "Frequency range", value: "20 Hz to 20,000 Hz" },
        ],
      },
      {
        sqlId: 7,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "RM" },
          { sqlId: "Wireless", value: true },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Latency", value: "less than 1ms" },
          { sqlId: "Noise cancelling", value: true },
          { sqlId: "Frequency range", value: "20 Hz to 20,000 Hz" },
        ],
      },
      {
        sqlId: 8,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 48 },
          { sqlId: "Thickness", value: 0.1 },
          { sqlId: "SmartTV", value: true },
          { sqlId: "Screen size", value: "60in" },
          { sqlId: "Resolution", value: "4K" },
        ],
      },
      {
        sqlId: 9,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 10 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
      {
        sqlId: 10,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 20 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
      {
        sqlId: 11,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Width", value: 5 },
          { sqlId: "Length", value: 8 },
          { sqlId: "Thickness", value: 0.25 },
          { sqlId: "Color", value: "Red" },
          { sqlId: "RAM", value: "16GB" },
          { sqlId: "CPU", value: "Quad-core" },
          { sqlId: "GPU", value: "Intel Graphic" },
          { sqlId: "Screen size", value: "20in" },
          { sqlId: "Storage capacity", value: "256GB" },
          { sqlId: "Resolution", value: "1080p" },
        ],
      },
      {
        sqlId: 12,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Refresh rate", value: "120Hz" },
          { sqlId: "Resolution", value: "1080p" },
          { sqlId: "Screen size", value: "20in" },
        ],
      },
      {
        sqlId: 13,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Color", value: "blue" },
          { sqlId: "Latency", value: "0.5ms" },
        ],
      },
      {
        sqlId: 14,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Wireless", value: true },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Latency", value: "less than 1ms" },
          { sqlId: "Noise cancelling", value: true },
          { sqlId: "Frequency range", value: "20 Hz to 20,000 Hz" },
        ],
      },
      {
        sqlId: 15,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 20 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
      {
        sqlId: 16,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Width", value: 5 },
          { sqlId: "Length", value: 8 },
          { sqlId: "Thickness", value: 0.25 },
          { sqlId: "Color", value: "Red" },
          { sqlId: "RAM", value: "16GB" },
          { sqlId: "CPU", value: "Quad-core" },
          { sqlId: "GPU", value: "Intel Graphic" },
          { sqlId: "Screen size", value: "20in" },
          { sqlId: "Storage capacity", value: "256GB" },
          { sqlId: "Resolution", value: "1080p" },
        ],
      },
      {
        sqlId: 17,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "RPM" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Refresh rate", value: "120Hz" },
          { sqlId: "Resolution", value: "1080p" },
          { sqlId: "Screen size", value: "20in" },
        ],
      },
      {
        sqlId: 18,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "KTL" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Color", value: "blue" },
          { sqlId: "Latency", value: "0.5ms" },
        ],
      },
      {
        sqlId: 19,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Wireless", value: true },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Latency", value: "less than 1ms" },
          { sqlId: "Noise cancelling", value: false },
          { sqlId: "Frequency range", value: "20 Hz to 20,000 Hz" },
        ],
      },
      {
        sqlId: 20,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 20 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
      {
        sqlId: 21,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Wireless", value: true },
          { sqlId: "Color", value: "blue" },
          { sqlId: "Latency", value: "0.5ms" },
        ],
      },
      {
        sqlId: 22,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "1 years" },
          { sqlId: "Brand", value: "Pineapple" },
          { sqlId: "Width", value: 4 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Thickness", value: 1 },
          { sqlId: "Color", value: "Silver" },
          { sqlId: "RAM", value: "2GB" },
          { sqlId: "CPU", value: "Duo-core" },
          { sqlId: "Storage capacity", value: "64GB" },
          { sqlId: "Resolution", value: "320p" },
        ],
      },
      {
        sqlId: 23,
        attributes: [
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "2 years" },
          { sqlId: "Brand", value: "Steinheiser" },
          { sqlId: "Wireless", value: true },
          { sqlId: "Battery powered", value: true },
          { sqlId: "Latency", value: "less than 1ms" },
          { sqlId: "Noise cancelling", value: false },
          { sqlId: "Frequency range", value: "20 Hz to 20,000 Hz" },
        ],
      },
      {
        sqlId: 24,
        attributes: [
          { sqlId: "Warranty", value: false },
          { sqlId: "Brand", value: "Pineapple" },
          { sqlId: "Color", value: "Pink" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "200W" },
          { sqlId: "SmartTV", value: false },
          { sqlId: "Screen size", value: "10in" },
          { sqlId: "Resolution", value: "320p" },
        ],
      },
      {
        sqlId: 25,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 20 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
      {
        sqlId: 26,
        attributes: [
          { sqlId: "Height", value: 3 },
          { sqlId: "Width", value: 20 },
          { sqlId: "Length", value: 6 },
          { sqlId: "Warranty", value: true },
          { sqlId: "Warranty period", value: "5 years" },
          { sqlId: "Brand", value: "Sumsang" },
          { sqlId: "Color", value: "Black" },
          { sqlId: "Voltage", value: "120V" },
          { sqlId: "Wattage", value: "180W" },
        ],
      },
    ]);

    console.log("Inserted mock data.");
    mongoose.connection.close();
  } catch (error) {
    console.log(`Failed to insert mock data: ${error}`);
    mongoose.connection.close();
  }
}

exports.insertMockData = insertMockData;
