USE isys2099_group9_app;


/* ===============
   WAREHOUSE TABLE

   These secondary indices are sufficient to aid the warehouse admin in efficient retrieval of warehouse data:

   - unidx_warehouse_warehouse_name: Faster retrieval of warehouses using their (unique) name - warehouse_name column.
   - idx_warehouse_volume: Faster retrieval of warehouses using their volume - volume column.
   - idx_warehouse_address: Faster retrieval of warehouses using their address - province, city, district, street, and
     street_number columns.
 */

ALTER TABLE warehouse ADD UNIQUE INDEX unidx_warehouse_warehouse_name (warehouse_name);
ALTER TABLE warehouse ADD INDEX idx_warehouse_volume (volume);
ALTER TABLE warehouse ADD INDEX idx_warehouse_address (province, city, district, street, street_number);


/* =============
   PRODUCT TABLE

   In addition to basic indices, this table also requires a fulltext index on the product_description column to aid in
   efficient data retrieval by the warehouse admin, seller, and buyer:

   - idx_product_title: Faster retrieval of products using their title - title column.
   - idx_fulltext_product_product_description: Faster **fulltext** search and filtering of products using their
     description - product_description column.
   - idx_product_category: Faster retrieval of products using their category - category column.
   - idx_product_price: Faster retrieval of products using their price - price column.
   - idx_product_dimensions: Faster retrieval of products using their 3 dimensions - width, length, and height columns.
   - idx_product_seller: Faster retrieval of products using their seller - seller column.
 */

ALTER TABLE product ADD INDEX idx_product_title (title);
ALTER TABLE product ADD FULLTEXT INDEX idx_fulltext_product_product_description (product_description);
ALTER TABLE product ADD INDEX idx_product_category (category);
ALTER TABLE product ADD INDEX idx_product_price (price);
ALTER TABLE product ADD INDEX idx_product_dimensions (width, length, height);
ALTER TABLE product ADD INDEX idx_product_seller (seller);


/* ===================
   INBOUND_ORDER TABLE

   These secondary indices are sufficient to aid the seller in efficient retrieval of inbound order data:

   - idx_inbound_order_quantity: Faster retrieval of inbound orders using their quantity - quantity column.
   - idx_inbound_order_product_id: Faster retrieval of inbound orders using their associated product - product_id
     column.
   - idx_inbound_order_created_datetime: Faster retrieval of inbound orders using their created date and time -
     created_date and created_time columns.
   - idx_inbound_order_fulfilled_datetime: Faster retrieval of inbound orders using their fulfilled date and time -
     fulfilled_date and fulfilled_time columns.
   - idx_inbound_order_seller: Faster retrieval of inbound orders using their seller - seller column.
 */

ALTER TABLE inbound_order ADD INDEX idx_inbound_order_quantity (quantity);
ALTER TABLE inbound_order ADD INDEX idx_inbound_order_product_id (product_id);
ALTER TABLE inbound_order ADD INDEX idx_inbound_order_created_datetime (created_date, created_time);
ALTER TABLE inbound_order ADD INDEX idx_inbound_order_fulfilled_datetime (fulfilled_date, fulfilled_time);
ALTER TABLE inbound_order ADD INDEX idx_inbound_order_seller (seller);


/* =================
   BUYER_ORDER TABLE

   These secondary indices are sufficient to aid the buyer in efficient retrieval of buyer order data:

   - idx_buyer_order_quantity: Faster retrieval of buyer orders using their quantity - quantity column.
   - idx_buyer_order_product_id: Faster retrieval of buyer orders using their associated product - product_id
     column.
   - idx_buyer_order_created_datetime: Faster retrieval of buyer orders using their created date and time -
     created_date and created_time columns.
   - idx_buyer_order_order_status: Faster retrieval of buyer orders using their status - order_status column.
   - idx_buyer_order_fulfilled_datetime: Faster retrieval of buyer orders using their fulfilled date and time -
     fulfilled_date and fulfilled_time columns.
   - idx_buyer_order_buyer: Faster retrieval of buyer orders using their seller - seller column.
 */

ALTER TABLE buyer_order ADD INDEX idx_buyer_order_quantity (quantity);
ALTER TABLE buyer_order ADD INDEX idx_buyer_order_product_id (product_id);
ALTER TABLE buyer_order ADD INDEX idx_buyer_order_created_datetime (created_date, created_time);
ALTER TABLE buyer_order ADD INDEX idx_buyer_order_order_status (order_status);
ALTER TABLE buyer_order ADD INDEX idx_buyer_order_fulfilled_datetime (fulfilled_date, fulfilled_time);
ALTER TABLE buyer_order ADD INDEX idx_buyer_order_buyer (buyer);


/* ============
   OTHER TABLES

   The structure of the remaining tables are simple enough for their primary index (automatically generated by MySQL on
   the primary key column) to be good enough for database performance.
 */
